### ISSUE TITLE
irregular convolution

### ISSUE THREAD

**Issue by xchhuang** [tph9608/Point-Synthesis#2]
Hi @tph9608, thanks for sharing the code.

I am wondering if the irregular convolution is implemented in the `Point2Image` and `SoftPoint2Image` classes ? And the `diff_func.py` is not used ? Thanks in advance.

**Comment by phtu-cs** [comment]
For the first question, yes;
For the second question, probably. The code is very old. Could you please set a break point or comment the diff_func out to see if it is used? Thank you.

**Comment by xchhuang** [comment]
Thanks for you reply @tph9608 .

I found that it's tested, but not used in either `hierarchical_end_to_end_optimization_sample_position` or `sample_merging_optimization`.

**Comment by phtu-cs** [comment]
Thank you for letting me know. Sorry that the research code is not very well written. Feel free to let me know if you have any other questions.
